# Generated by Django 5.1 on 2025-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
    ]
