# Generated by Django 5.1 on 2025-06-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0002_products_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
