# Generated by Django 5.1 on 2025-06-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0003_products_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
