# Generated by Django 5.1 on 2025-01-02 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('senha', models.CharField(default='senha123', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('foto_perfil', models.ImageField(upload_to='images')),
                ('cpf', models.CharField(max_length=14)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('senha', models.CharField(default='senha123', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('foto_perfil', models.ImageField(upload_to='images')),
                ('celular', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=14)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
