# Generated by Django 5.1 on 2025-06-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_cliente_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
