# Generated by Django 5.1 on 2025-06-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_administrador_is_admin_cliente_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='celular',
            field=models.CharField(default='00000000000', max_length=11),
            preserve_default=False,
        ),
    ]
